### ISSUE TITLE
confused about Readme and how to skip object?

### ISSUE THREAD

**Issue by weiXiaxvv** [montescene/demo#1]
Hi @vevenom 
Thanks for sharing the code and it is a really good work.

I have some problems when I tried to run the project.

1. Download the ShapenetV2 dataset by signing up on the website. Extract the models to $SHAPENET_DIR
I am confused about the $SHAPENET_DIR, it is a folder or anything else?
2. If I need to set the bool to True in demo.py to skip_object in line 17. I only need the layout part
```
flags.DEFINE_string('scene', 'scene0000_00', 'scene ID')
flags.DEFINE_string('shapenet_dir', '/media/xvv/4aa82be1-14a8-47f7-93a7-171e3ebac2b0/Datasets/ShapeNetCore.v2', 'shapenet dir')
flags.DEFINE_bool('skip_objects', False, 'skip adding objects to the scene')
flags.DEFINE_bool('skip_layout', False, 'skip adding room layout to the `scene')`
```
Thanks a lot, good work again :).
Kind regards
Wei

**Comment by shreyashampali** [comment]
Hi Wei,
Thanks for your interest in our work.
If you want to skip the objects in demo.py, you could simply do:
`python demo.py --skip_objects`
$SHAPENET_DIR is the name of the shapenet directory you download. You do not need to download this if you are interested only in layouts.

thanks,
Shreyas

**Comment by weiXiaxvv** [comment]
Hi @vevenom 
Thanks for ur reply that is really helpful(save brunch of time to download the dataset lol!)
I could run the demo.py by your suggestion, However this is the result I got
![Screenshot from 2021-05-15 01-48-59](https://user-images.githubusercontent.com/44054965/118349657-e7a69600-b51f-11eb-8d4b-c27d9eb19fae.png)
There is no red line to highlight the layout as shown in paper
The terminal shows "WARNING: Layout missing for scene scene0593_00", and I checked the code:
"outputs/scans/", sceneID, 'monte_carlo/FinalLayout.pickle'
There is no FinalLayout.pickle file but a FinalCandidates.pickle file.
Is there anything else I might miss?

Sincerely thanks for your answer!

Kind regards,
Wei

**Comment by vevenom** [comment]
Hi Wei, 

note that for some scenes the room layouts are indeed missing. We provided layouts only for the validation set on a different subset of scenes based on the SceneCAD dataset. This set of scenes coincides with the manual annotations you can download [here](https://files.icg.tugraz.at/f/dbcbed1299e2415a9315/?dl=1). SceneCAD seems to have discarded scenes where, for example, a large/complete portions of walls is invisible, hence estimating layouts on such scenes makes less sense, so we follow this reasoning (not sure why scene0593_00 was not in the SceneCAD dataset, seems to be quite complete).

Thanks,
Sinisa

**Comment by weiXiaxvv** [comment]
Hi @vevenom
It seems the FinalLayout.pickle is necessary to demo the layout. Could I run the project on another dataset like Synthesis data?
And I want to check if the FinalLayout.pickle is offered by the dataset? I am a little bit confused about the FinalLayout.pickle file, it is manual annotation file or generated file or something else??

Kind regards
Wei

**Comment by vevenom** [comment]
> Could I run the project on another dataset like Synthesis data?

As explained in the Readme, this project merely shows visualizations of the scene understanding results  of our approach. The implementation of the method itself is not available currently. So, no.

> I am a little bit confused about the FinalLayout.pickle file, it is manual annotation file or generated file or something else??

The included *.pickle files are pre-generated results of our MCSS approach.

**Comment by weiXiaxvv** [comment]
Hi @vevenom

If the included *.pickle files pre-generated approach is not available right now? I ran the demo.py and eval_layouts and checked the code, it seems no file is generated. As far as I know, the .pickle file needs to be generated by pickle.dump(), and I can not find those code inside project. 

Kind regards
Wei

**Comment by vevenom** [comment]
As stated in the readme, all pre-generated files can be downloaded [here](https://files.icg.tugraz.at/f/3ab82b7d215143cdb1f7/?dl=1). After extracting the .zip file to the `outputs` folder you should be able to run the demo for the provided scenes.
